server:
  port: 8787
  ssl:
    enabled: ${SSL:false}
    key-store-type: PKCS12
    key-store: ${KEY_STORE:classpath:microservices.p12}
    key-store-password: ${KEY_STORE_PASSWORD:password}
    key-alias: ${KEY_STORE_ALIAS:192.168.68.102}
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    secure-port-enabled: ${server.ssl.enabled}
    secure-port: ${server.port}
spring:
  application:
    name: ConfigServer
  profiles:
    active:
    - dev
  cloud:
    config:
      username: ${CONFIG_USERNAME:default}
      password: ${CONFIG_PASSWORD:password}
      server:
        encrypt:
          enabled: true