server:
  port: 8787
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: ConfigServer
  profiles:
    active:
    - dev