INSERT IGNORE INTO oauth_client_details
(client_id,
resource_ids,
client_secret,
scope,
authorized_grant_types,
web_server_redirect_uri,
authorities,
access_token_validity,
refresh_token_validity,
additional_information,
autoapprove)
VALUES
('serviceclientid',
NULL,
'$2y$12$rDbNHb7hOtOAtYbNVl.5Oe2sj.IjXPstSue3t.lxsDhA6pngEfesu',
'greet,userinfo',
'client_credentials',
NULL,
'ROLE_SERVICE',
120,
86400,
NULL,
true);
